#cloud-config

# Install Flynn
runcmd:
- curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
- bash /tmp/install-flynn

users:
- default
- name: flynn
  gecos: Flynn User
  sudo: ALL=(ALL:ALL) ALL
  passwd: ${password_hash}
  lock_passwd: false
  ssh_authorized_keys:
    - ${public_key}

